version: '3.8'

services:
    app:
        build:
            context: .
        container_name: laravel-app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./db:/var/www/html/db
        environment:
            - APP_ENV=local
            - LOG_REQUESTS=true
